### ISSUE TITLE
部署在render无法使用WebDAV

### ISSUE THREAD

**Issue by ChirmyRam** [alist-org/alist-render#2]
使用WebDAV客户端 Mixplorer 连接时提示 Response failure 405 ，其他WebDAV客户端客户端也无法连接，这是render对实例做了什么限制吗？

**Comment by Xhofe** [comment]
405就是method不允许，他可能只允许标准的http method，而WebDAV的propfind等method并不是。

**Comment by ChirmyRam** [comment]
明白，感谢
